In [2]:
import numpy as np

Sayılardan oluşan bir boyutlu array oluşturulur. Arrayi oluştururken sayıların veri tipini integer olarak belirtilir. Oluşturulan arrayin boyut, eleman sayısı bilgilerine bakılır.


In [3]:
array = np.array([1, 2, 3, 4, 5], dtype=int) 
array 

array([1, 2, 3, 4, 5])

In [4]:
array.ndim 

1

In [5]:
len(array)

5

İki ve üç boyutlu arrayler oluşturulur. Bu arraylerin boyut, eleman sayısı, satır, sütun bilgilerine ulaşılır. Arrayler üzerinde indexleme ve dilimleme(slicing) işlemi yapılır.

In [6]:
array2 = np.array([[1, 2, 3, 4, 5]])
array2

array([[1, 2, 3, 4, 5]])

In [7]:
array3 = np.array([[[18, 21, 42, 57]],[[12, 13, 76, 3]],[[18, 5, 4, 57]],[[1, 13, 76, 3]]])
#dilimleme
array3[0:3]

array([[[18, 21, 42, 57]],

       [[12, 13, 76,  3]],

       [[18,  5,  4, 57]]])

In [8]:
array2.ndim

2

In [9]:
array3.ndim

3

In [10]:
len(array2)

1

In [11]:
len(array3)

4

In [12]:
array2.shape

(1, 5)

In [13]:
array3.shape

(4, 1, 4)

In [14]:
array3

array([[[18, 21, 42, 57]],

       [[12, 13, 76,  3]],

       [[18,  5,  4, 57]],

       [[ 1, 13, 76,  3]]])

In [15]:
array2

array([[1, 2, 3, 4, 5]])

In [16]:
array3[1]

array([[12, 13, 76,  3]])

In [17]:
array3[-2]

array([[18,  5,  4, 57]])

In [18]:
array3

array([[[18, 21, 42, 57]],

       [[12, 13, 76,  3]],

       [[18,  5,  4, 57]],

       [[ 1, 13, 76,  3]]])

Sıfırlardan oluşan ve birlerden oluşan iki tane iki boyutlu array oluşturulur. Bu arrayler satır ve sütun bazında birleştirilir.

In [19]:
sifir_array = np.zeros((3, 3))
bir_array = np.ones((3, 3))

In [20]:
satir_birlestirelim = np.concatenate((sifir_array, bir_array), axis=0)
print("Satır bazında birleştirme:")
print(satir_birlestirelim)

Satır bazında birleştirme:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [21]:
sutun_birlestirilmis = np.concatenate((sifir_array, bir_array), axis=1)
print("\nSütün bazında birleştirme:")
print(bir_array)


Sütün bazında birleştirme:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
